/*******************************************************************************************************************
Task Number :    AH4.FF004  
                                                                                                                      
Program Name:    \\\programs.ahrq.local\programs\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Prog\SAS\QC_PCTPOP_Cross1.sas 
                                                                                               
Description :   QC the calculated coefficent and standard error estimates for percent (%) of population
								with an expense (PCTPOP), Cross Sectional Tables:
								(1) Demographics x Demographics, Health Variables, Socio-Economic Status
										(a) Demographic Variables: Age Groups, Census Regions, Marital Status, Race/Ethnicity, Sex
										(b) Health Variables: Insurance Coverage, Perceived Health Status, Perceived Mental Status
										(c) Socio-Economic Stauts Variables: Education, Employment Status, Poverty Status
                
                Compare against the R Shiny Server estimates.
                                                                                                                                                                                          
Input Data:	   \\derived.ahrq.local\Derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Data\PERSdata9614V2.sas7bdat 
							 \\derived.ahrq.local\derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\R_Estimates\V4\std_fyc9614.sas7bdat 
                                                  
Programmer  :   Jodi Cisewski                                                                                                                                     

Date        :    June 11, 2017
********************************************************************************************************************/
OPTIONS LS=200 PS=60 OBS=MAX;

libname SAS "\\derived.ahrq.local\Derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Data" access=readonly;
libname Rest "\\derived.ahrq.local\derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\R_Estimates\V4" access=readonly; 

TITLE1 "AH4.FF004:  MEPS-HC: Utilization and Expenditures, 1996-2014";


%include "\\programs.ahrq.local\programs\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Prog\SAS\Jodi\QC\formats.sas";
						
%let combo = 	AGEGRPS*REGION AGEGRPS*MARRIED AGEGRPS*RACE AGEGRPS*SEX
							AGEGRPS*INSURANCE AGEGRPS*INSURANCE_V2 AGEGRPS*HEALTH AGEGRPS*MENTAL_HEALTH
							AGEGRPS*EDUCATION AGEGRPS*EMPLOYED AGEGRPS*POVERTY
							AGEGRPS_V2*REGION AGEGRPS_V2*MARRIED AGEGRPS_V2*RACE  AGEGRPS_V2*SEX
							AGEGRPS_V2*INSURANCE  AGEGRPS_V2*INSURANCE_V2  AGEGRPS_V2*HEALTH  AGEGRPS_V2*MENTAL_HEALTH
							AGEGRPS_V2*EDUCATION  AGEGRPS_V2*EMPLOYED  AGEGRPS_V2*POVERTY
							REGION*MARRIED REGION*RACE REGION*SEX 
							REGION*INSURANCE REGION*INSURANCE_V2 REGION*HEALTH REGION*MENTAL_HEALTH
							REGION*EDUCATION REGION*EMPLOYED REGION*POVERTY
							MARRIED*RACE MARRIED*SEX
							MARRIED*INSURANCE MARRIED*INSURANCE_V2 MARRIED*HEALTH MARRIED*MENTAL_HEALTH
							MARRIED*EDUCATION MARRIED*EMPLOYED MARRIED*POVERTY
							RACE*SEX
							RACE*INSURANCE RACE*INSURANCE_V2 RACE*HEALTH RACE*MENTAL_HEALTH
							RACE*EDUCATION RACE*EMPLOYED RACE*POVERTY
							SEX*INSURANCE SEX*INSURANCE_V2 SEX*HEALTH SEX*MENTAL_HEALTH
							SEX*EDUCATION SEX*EMPLOYED SEX*POVERTY
							;
	
								
%let demo = AGEGRPS AGEGRPS_V2 REGION MARRIED RACE SEX;
%let health =  INSURANCE INSURANCE_V2 HEALTH MENTAL_HEALTH; 
%let soceco = EDUCATION EMPLOYED POVERTY;	



%MACRO YY (YEAR=);

DATA FY&YEAR (KEEP = TESTVAR IND VARPSU VARSTR PERWTF YEAR TOTAL &demo &health &soceco);
  SET SAS.PERSDATA9614V2 (WHERE=(YEAR=&YEAR));
  TOTAL=1;
  /*create dummy variable for people who have an expense*/
  IF TOTEXP > 0 THEN TESTVAR=1;
  ELSE TESTVAR=0;
RUN;



ODS LISTING CLOSE;
PROC SURVEYMEANS DATA=FY&YEAR NOMCAR mean stderr;
VAR TESTVAR;
CLUSTER VARPSU; 
STRATA VARSTR;
WEIGHT PERWTF;
DOMAIN &COMBO;
ODS OUTPUT domain=OUT1;
RUN;
ODS LISTING;


DATA OUT&YEAR;
  SET OUT1; 
 LENGTH grp1 grp2 $15  levels1 LEVELS2 $255;
 IF DOMAINLABEL =: 			"Age group: 0-4, 5-17, 18-44, 45-64, 65+*" 	then do; grp1='AGEGRPS'; 				LEVELS1=PUT(AGEGRPS, AGEGRPS.); end;
 ELSE IF DOMAINLABEL =: "Age group: 0-17, 18-64, 65+*" 							then do; grp2='AGEGRPS_V2'; 		LEVELS2=PUT(AGEGRPS_V2, AGEGRPS_V2x.); end;
 ELSE IF DOMAINLABEL =: "REGIONyy/42/31*" 													then do; grp1='REGION'; 				LEVELS1=PUT(REGION, REGION.); end; 
 ELSE IF DOMAINLABEL =: "MARRYyy/42/31X*" 													then do; grp1='MARRIED'; 				LEVELS1=PUT(MARRIED, MARRIED.); end;
 ELSE IF DOMAINLABEL =: "RACE/ETHNICITY*" 													then do; grp1='RACE'; 					LEVELS1=PUT(RACE, RACE.); end;
 ELSE IF DOMAINLABEL =: "GENDER*" 																	then do; grp1='SEX'; 					  LEVELS1=PUT(SEX, SEX.); END; 
 YEAR=&YEAR;
RUN;



DATA  OUT&YEAR._NEW /*(KEEP=YEAR grp1 grp2 MEAN STDERR levels1 levels2 WHERE=(grp2 NE " "))*/;
SET OUT&YEAR;
*AGEGRPS;
    IF GRP1="AGEGRPS" AND REGION>0 THEN DO; grp2='REGION'; LEVELS2=PUT(REGION, REGION.); END;
    ELSE IF GRP1="AGEGRPS" AND MARRIED>0 OR MARRIED=-1 THEN DO; grp2='MARRIED'; LEVELS2=PUT(MARRIED, MARRIED.); END;
    ELSE IF GRP1="AGEGRPS" AND RACE>0 THEN DO; grp2='RACE'; LEVELS2=PUT(RACE, RACE.); END;
    ELSE IF GRP1="AGEGRPS" AND SEX>0 THEN DO; grp2='SEX'; LEVELS2=PUT(SEX, SEX.); END;
    ELSE IF GRP1="AGEGRPS" AND INSURANCE>0 THEN DO; grp2='INSURANCE'; LEVELS2=PUT(INSURANCE, INSURANCE.); END;
    ELSE IF GRP1="AGEGRPS" AND INSURANCE_V2>0 THEN DO; grp2='INSURANCE_V2'; LEVELS2=PUT(INSURANCE_V2, INSURANCE_V2x.); END;
    ELSE IF GRP1="AGEGRPS" AND HEALTH>0 THEN DO; grp2='HEALTH'; LEVELS2=PUT(HEALTH, HEALTH.); END;
    ELSE IF GRP1="AGEGRPS" AND MENTAL_HEALTH>0 THEN DO; grp2='MENTAL_HEALTH'; LEVELS2=PUT(MENTAL_HEALTH, MENTAL_HEALTH.);END;
    ELSE IF GRP1="AGEGRPS" AND EDUCATION>0 OR EDUCATION=-1 THEN DO; grp2='EDUCATION'; LEVELS2=PUT(EDUCATION, EDUCATION.); END;
    ELSE IF GRP1="AGEGRPS" AND EMPLOYED>0 OR EMPLOYED=-1 THEN DO; grp2='EMPLOYED'; LEVELS2=PUT(EMPLOYED, EMPLOYED.); END;
    ELSE IF GRP1="AGEGRPS" AND POVERTY>0 THEN DO; grp2='POVERTY'; LEVELS2=PUT(POVERTY, POVERTY.); END; 

  
 *agegrps_v2;
   	IF GRP2="AGEGRPS_V2" AND REGION>0 THEN DO; grp1='REGION'; LEVELS1=PUT(REGION, REGION.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND MARRIED>0 OR MARRIED=-1 THEN DO; grp1='MARRIED'; LEVELS1=PUT(MARRIED, MARRIED.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND RACE>0 THEN DO; grp1='RACE'; LEVELS1=PUT(RACE, RACE.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND SEX>0 THEN DO; grp1='SEX'; LEVELS1=PUT(SEX, SEX.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND INSURANCE>0 THEN DO; grp1='INSURANCE'; LEVELS1=PUT(INSURANCE, INSURANCE.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND INSURANCE_V2>0 THEN DO; grp1='INSURANCE_V2'; LEVELS1=PUT(INSURANCE_V2, INSURANCE_V2x.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND HEALTH>0 THEN DO; grp1='HEALTH'; LEVELS1=PUT(HEALTH, HEALTH.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND  MENTAL_HEALTH>0 THEN DO; grp1='MENTAL_HEALTH'; LEVELS1=PUT(MENTAL_HEALTH, MENTAL_HEALTH.);END;
    ELSE IF GRP2="AGEGRPS_V2" AND EDUCATION>0 OR EDUCATION=-1 THEN DO; grp1='EDUCATION'; LEVELS1=PUT(EDUCATION, EDUCATION.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND EMPLOYED>0 OR EMPLOYED=-1 THEN DO; grp1='EMPLOYED'; LEVELS1=PUT(EMPLOYED, EMPLOYED.); END;
    ELSE IF GRP2="AGEGRPS_V2" AND POVERTY>0 THEN DO; grp1='POVERTY'; LEVELS1=PUT(POVERTY, POVERTY.); END; 

 
 *region;
    IF GRP1="REGION" AND MARRIED>0 OR MARRIED=-1 THEN DO; grp2='MARRIED'; LEVELS2=PUT(MARRIED, MARRIED.); END;
    ELSE IF GRP1="REGION" AND RACE>0 THEN DO; grp2='RACE'; LEVELS2=PUT(RACE, RACE.); END;
    ELSE IF GRP1="REGION" AND SEX>0 THEN DO; grp2='SEX'; LEVELS2=PUT(SEX, SEX.); END;
    ELSE IF GRP1="REGION" AND INSURANCE>0 THEN DO; grp2='INSURANCE'; LEVELS2=PUT(INSURANCE, INSURANCE.); END;
    ELSE IF GRP1="REGION" AND INSURANCE_V2>0 THEN DO; grp2='INSURANCE_V2'; LEVELS2=PUT(INSURANCE_V2, INSURANCE_V2x.); END;
    ELSE IF GRP1="REGION" AND HEALTH>0 THEN DO; grp2='HEALTH'; LEVELS2=PUT(HEALTH, HEALTH.); END;
    ELSE IF GRP1="REGION" AND MENTAL_HEALTH>0 THEN DO; grp2='MENTAL_HEALTH'; LEVELS2=PUT(MENTAL_HEALTH, MENTAL_HEALTH.);END;
    ELSE IF GRP1="REGION" AND EDUCATION>0 OR EDUCATION=-1 THEN DO; grp2='EDUCATION'; LEVELS2=PUT(EDUCATION, EDUCATION.); END;
    ELSE IF GRP1="REGION" AND EMPLOYED>0 OR EMPLOYED=-1 THEN DO; grp2='EMPLOYED'; LEVELS2=PUT(EMPLOYED, EMPLOYED.); END;
    ELSE IF GRP1="REGION" AND POVERTY>0 THEN DO; grp2='POVERTY'; LEVELS2=PUT(POVERTY, POVERTY.); END;  

  
  *marriage; 
    IF GRP1="MARRIED" AND RACE>0 THEN DO; grp2='RACE'; LEVELS2=PUT(RACE, RACE.); END;
    ELSE IF GRP1="MARRIED" AND SEX>0 THEN DO; grp2='SEX'; LEVELS2=PUT(SEX, SEX.); END;
    ELSE IF GRP1="MARRIED" AND INSURANCE>0 THEN DO; grp2='INSURANCE'; LEVELS2=PUT(INSURANCE, INSURANCE.); END;
    ELSE IF GRP1="MARRIED" AND INSURANCE_V2>0 THEN DO; grp2='INSURANCE_V2'; LEVELS2=PUT(INSURANCE_V2, INSURANCE_V2x.); END;
    ELSE IF GRP1="MARRIED" AND HEALTH>0 THEN DO; grp2='HEALTH'; LEVELS2=PUT(HEALTH, HEALTH.); END;
    ELSE IF GRP1="MARRIED" AND MENTAL_HEALTH>0 THEN DO; grp2='MENTAL_HEALTH'; LEVELS2=PUT(MENTAL_HEALTH, MENTAL_HEALTH.);END;
    ELSE IF GRP1="MARRIED" AND EDUCATION>0 OR EDUCATION=-1 THEN DO; grp2='EDUCATION'; LEVELS2=PUT(EDUCATION, EDUCATION.); END;
    ELSE IF GRP1="MARRIED" AND EMPLOYED>0 OR EMPLOYED=-1 THEN DO; grp2='EMPLOYED'; LEVELS2=PUT(EMPLOYED, EMPLOYED.); END;
    ELSE IF GRP1="MARRIED" AND POVERTY>0 THEN DO; grp2='POVERTY'; LEVELS2=PUT(POVERTY, POVERTY.); END; 
   
   *race;
    IF GRP1="RACE" AND SEX>0 THEN DO; grp2='SEX'; LEVELS2=PUT(SEX, SEX.); END;
    ELSE IF GRP1="RACE" AND INSURANCE>0 THEN DO; grp2='INSURANCE'; LEVELS2=PUT(INSURANCE, INSURANCE.); END;
    ELSE IF GRP1="RACE" AND INSURANCE_V2>0 THEN DO; grp2='INSURANCE_V2'; LEVELS2=PUT(INSURANCE_V2, INSURANCE_V2x.); END;
    ELSE IF GRP1="RACE" AND HEALTH>0 THEN DO; grp2='HEALTH'; LEVELS2=PUT(HEALTH, HEALTH.); END;
    ELSE IF GRP1="RACE" AND MENTAL_HEALTH>0 THEN DO; grp2='MENTAL_HEALTH'; LEVELS2=PUT(MENTAL_HEALTH, MENTAL_HEALTH.);END;
    ELSE IF GRP1="RACE" AND EDUCATION>0 OR EDUCATION=-1 THEN DO; grp2='EDUCATION'; LEVELS2=PUT(EDUCATION, EDUCATION.); END;
    ELSE IF GRP1="RACE" AND EMPLOYED>0 OR EMPLOYED=-1 THEN DO; grp2='EMPLOYED'; LEVELS2=PUT(EMPLOYED, EMPLOYED.); END;
    ELSE IF GRP1="RACE" AND POVERTY>0 THEN DO; grp2='POVERTY'; LEVELS2=PUT(POVERTY, POVERTY.); END;  
 
 
    *sex;
		IF GRP1="SEX" AND INSURANCE>0 THEN DO; grp2='INSURANCE'; LEVELS2=PUT(INSURANCE, INSURANCE.); END;
    ELSE IF GRP1="SEX" AND INSURANCE_V2>0 THEN DO; grp2='INSURANCE_V2'; LEVELS2=PUT(INSURANCE_V2, INSURANCE_V2x.); END;
    ELSE IF GRP1="SEX" AND HEALTH>0 THEN DO; grp2='HEALTH'; LEVELS2=PUT(HEALTH, HEALTH.); END;
    ELSE IF GRP1="SEX" AND MENTAL_HEALTH>0 THEN DO; grp2='MENTAL_HEALTH'; LEVELS2=PUT(MENTAL_HEALTH, MENTAL_HEALTH.);END;
    ELSE IF GRP1="SEX" AND EDUCATION>0 OR EDUCATION=-1 THEN DO; grp2='EDUCATION'; LEVELS2=PUT(EDUCATION, EDUCATION.); END;
    ELSE IF GRP1="SEX" AND EMPLOYED>0 OR EMPLOYED=-1 THEN DO; grp2='EMPLOYED'; LEVELS2=PUT(EMPLOYED, EMPLOYED.); END;
    ELSE IF GRP1="SEX" AND POVERTY>0 THEN DO; grp2='POVERTY'; LEVELS2=PUT(POVERTY, POVERTY.); END;   
RUN;

 %MEND YY;

 %YY (YEAR=2014)
 %YY (YEAR=2013)
 %YY (YEAR=2012)
 %YY (YEAR=2011)
 %YY (YEAR=2010)
 %YY (YEAR=2009)
 %YY (YEAR=2008)
 %YY (YEAR=2007)
 %YY (YEAR=2006)
 %YY (YEAR=2005)
 %YY (YEAR=2004)
 %YY (YEAR=2003)
 %YY (YEAR=2002)
 %YY (YEAR=2001)
 %YY (YEAR=2000)
 %YY (YEAR=1999)
 %YY (YEAR=1998)
 %YY (YEAR=1997)
 %YY (YEAR=1996);
 
 
 data comb;
   set 
   out2014_NEW
   out2013_NEW
   out2012_NEW
   out2011_NEW
   out2010_NEW
   out2009_NEW
   out2008_NEW
   out2007_NEW
   out2006_NEW
   out2005_NEW
   out2004_NEW
   out2003_NEW
   out2002_NEW
   out2001_NEW
   out2000_NEW
   out1999_NEW
   out1998_NEW
   out1997_NEW
   out1996_NEW;
 run;
 


PROC SORT DATA=Rest.std_fyc9614 OUT=RShiny (WHERE=(GRP1 NE 'IND' AND  GRP1 NE 'SOP' AND GRP2 NE 'SOP' AND GRP2 NE 'EVENT') KEEP=GRP1 LEVELS1 GRP2 LEVELS2 PCTEXP PCTEXP_SE YEAR);
BY  GRP1 GRP2 LEVELS1 LEVELS2 YEAR;
RUN;


DATA RShiny2;
SET RShiny;
LENGTH grp3 grp4 $15  LEVELS3 LEVELS4 $255; 
GRP3=LOWCASE(COMPRESS(grp1));
LEVELS3=LOWCASE(COMPRESS(levels1));
GRP4=LOWCASE(COMPRESS(GRP2));
LEVELS4=LOWCASE(COMPRESS(LEVELS2));
MEAN_R=PCTEXP;
SE_R=PCTEXP_SE;
RUN;


DATA RESULT2;
SET COMB;
LENGTH grp3 grp4 $15  LEVELS3 LEVELS4 $255;
GRP3=LOWCASE(COMPRESS(grp1));
LEVELS3=LOWCASE(COMPRESS(levels1));
GRP4=LOWCASE(COMPRESS(GRP2));
LEVELS4=LOWCASE(COMPRESS(LEVELS2));
MEAN_SAS=ROUND(MEAN,0.001);
SE_SAS=ROUND(STDERR,0.001);
RUN;


PROC SORT DATA=RESULT2;
BY GRP3 GRP4 LEVELS3 LEVELS4 YEAR ;
RUN;

PROC SORT DATA=RShiny2;
BY GRP3 GRP4 LEVELS3 LEVELS4 YEAR ;
RUN;


DATA ALL;
MERGE RESULT2(IN=A KEEP=YEAR GRP3 GRP4 LEVELS3 LEVELS4 MEAN_SAS SE_SAS) RShiny2 (IN=B KEEP=YEAR GRP3 GRP4 LEVELS3 LEVELS4 MEAN_R SE_R);
BY GRP3 GRP4 LEVELS3 LEVELS4 YEAR;
IF A;
DIFF_MEAN=SUM(MEAN_R,-MEAN_SAS);
DIFF_SE=SUM(SE_R,-SE_SAS);
RUN;
 
 
TITLE2 "% of Population with an Expense: EVENTS x Demo, 1996-2014";
PROC PRINT DATA=ALL;
VAR YEAR GRP3 GRP4 LEVELS3 LEVELS4 MEAN_R MEAN_SAS DIFF_MEAN SE_R SE_SAS DIFF_SE;
where (DIFF_MEAN NE 0 OR DIFF_SE NE 0) AND (GRP3 NE "employed" AND GRP4 NE "employed") ; *Occur when  employment status= "inapplicable(age<16) and when age is greater than 16...these are not applicable;
RUN;