%JOBSTART;
*********************************************************************
 * Task Number :    AH4.FF004                                                                                                                        
 * Program Name:    \\\programs.ahrq.local\programs\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Prog\SAS\TOTEVT_cross2.sas                                                                                                
 * Description :    Calculate cross section estimates - TOTEXP by EVENT*SOP and compare them with V4 of R estimates for 1996-2014                                                                                                                                                                                                
 * Input Data:	   \\derived.ahrq.local\Derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Data\PERSDATA9614, EVTdata9614.sas7bdat  
 *                  \\derived.ahrq.local\derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\R_Estimates\V4\EVT9614
 * Output Data :    no                                                      
 * Programmer  :    Bidong Liu                                                                                                                                      
 * Date        :    5/31/2017
*********************************************************************;
OPTIONS LS=200 PS=60 OBS=MAX ;
libname task "\\derived.ahrq.local\Derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\Data";
libname V4R "\\derived.ahrq.local\derived\MEPS\AHRQ4_CY2\F_DSO\FF004ETH\R_Estimates\V4";

title1 "AH4.FF004";
PROC FORMAT;
VALUE AGEGRPS
1='UNDER 5'
2='5-17'
3='18-44'
4='45-64'
5='65+'
;
VALUE AGEGRPS_V2X
1='UNDER 18'
2='18-64'
3='65+'
;

VALUE MARRIED
.='. MISSING'
1='MARRIED'
2='WIDOWED'
3='DIVORCED'
4='SEPARATED'
5='NEVER MARRIED'
6='Inapplicable (age < 16)'
;

VALUE INSURANCE
1='ANY PRIVATE'
2='PUBLIC ONLY'
3='UNINSURED'
;

VALUE HEALTH
.=". MISSING" 
1='EXCELLENT' 
2='VERY GOOD' 
3='GOOD' 
4='FAIR' 
5='POOR'
;

VALUE MENTAL_HEALTH
.=". MISSING"
1='EXCELLENT'
2='VERY GOOD'
3='GOOD'
4='FAIR'
5='POOR'
;

VALUE EMPLOYED
.='. MISSING'
-1='Inapplicable (age < 16)'
1='EMPLOYED'
2='NOT EMPLOYED'
;

VALUE RACE
1='HISPANIC'
2='WHITE'
3='BLACK'
4='American Indian, Alaska Native,'
5='Asian, Hawaiian, or Pacific Isla'
9='WHITE AND OTHER'
;

VALUE EDUCATION
.='. MISSING'
1='LESS THAN HIGH SCHOOL'
2='HIGH SCHOOL'
3='SOME COLLEGE'
4='Inapplicable (age < 18)'
;

VALUE insurance_v2X
1='<65, Any private'
2='<65, Public only'
3='<65, UNINSURED'
4='65+, MEDICARE ONLY'
5='65+, Medicare and private'
6='65+, Medicare and other public'
7='65+, NO MEDICARE'
;

VALUE POVERTY
1='Negative or Poor'
2='Near-poor'
3='LOW INCOME'
4='MIDDLE INCOME'
5='HIGH INCOME'
;

VALUE SEX
1='Male'
2='Female';

VALUE REGION
1='NORTHEAST'
2='MIDWEST'
3='SOUTH'
4='WEST';

VALUE IND
1='Total';
RUN;



DATA RESULT;
   LENGTH  LEVELS2 $32;
levels2="XXXXXXXXXXXXXXXXX";
IF _N_ LT 0;
RUN;


%MACRO YY;
%DO YEAR=1996 %TO 2014;

TITLE3 "YEAR=&YEAR";

DATA FY;
  SET TASK.PERSDATA9614V2 (WHERE=(YEAR=&YEAR));
  TOTAL=1;
RUN;

ODS LISTING CLOSE;
PROC SURVEYMEANS DATA=FY SUM STD  missing;
VAR SOP1dvexp SOP1rxexp SOP1obexp  SOP1obexp_DR  SOP1obexp_OT  SOP1opexp SOP1opexp_DR SOP1opexp_OT SOP1erexp SOP1ipexp SOP1hhexp SOP1hhexp_A  SOP1hhexp_N  SOP1otexp
SOP2dvexp SOP2rxexp SOP2obexp  SOP2obexp_DR  SOP2obexp_OT  SOP2opexp SOP2opexp_DR SOP2opexp_OT SOP2erexp SOP2ipexp SOP2hhexp SOP2hhexp_A  SOP2hhexp_N  SOP2otexp
SOP3dvexp SOP3rxexp SOP3obexp  SOP3obexp_DR  SOP3obexp_OT  SOP3opexp SOP3opexp_DR SOP3opexp_OT SOP3erexp SOP3ipexp SOP3hhexp SOP3hhexp_A  SOP3hhexp_N  SOP3otexp
SOP4dvexp SOP4rxexp SOP4obexp  SOP4obexp_DR  SOP4obexp_OT  SOP4opexp SOP4opexp_DR SOP4opexp_OT SOP4erexp SOP4ipexp SOP4hhexp SOP4hhexp_A  SOP4hhexp_N  SOP4otexp
SOP5dvexp SOP5rxexp SOP5obexp  SOP5obexp_DR  SOP5obexp_OT  SOP5opexp SOP5opexp_DR SOP5opexp_OT SOP5erexp SOP5ipexp SOP5hhexp SOP5hhexp_A  SOP5hhexp_N  SOP5otexp
;
CLUSTER VARPSU; 
STRATA VARSTR;
WEIGHT PERWTF;
DOMAIN TOTAL ;
ODS OUTPUT domain=OUT;
RUN;
ODS LISTING;

DATA OUT1;
SET OUT;
YEAR=&YEAR;
RUN;

DATA RESULT;
SET RESULT OUT1;
RUN;

%END;
%MEND YY;
%YY


data RESULT1 ( KEEP=GRP: LEVELS: SUM STDDEV YEAR);
set RESULT;
  LENGTH grp2 grp1 $15  LEVELS2 levels1 $32;

  IF VARNAME="SOP1DVEXP" THEN DO; GRP1="EVENT"; LEVELS1="DVT"; GRP2="SOP"; LEVELS2="SLF";END;
  ELSE IF VARNAME="SOP1RXEXP" THEN DO; GRP1="EVENT"; LEVELS1="RX";GRP2="SOP"; LEVELS2="SLF";END;
  ELSE IF VARNAME="SOP1OBEXP" THEN DO; GRP1="EVENT"; LEVELS1="OBV";GRP2="SOP"; LEVELS2="SLF";END;  
  ELSE IF VARNAME="SOP1OBEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OBD";GRP2="SOP"; LEVELS2="SLF";END;    
  ELSE IF VARNAME="SOP1OBEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OBO";GRP2="SOP"; LEVELS2="SLF";END;    
  ELSE IF VARNAME="SOP1OPEXP" THEN DO; GRP1="EVENT"; LEVELS1="OPT";GRP2="SOP"; LEVELS2="SLF";END;    
  ELSE IF VARNAME="SOP1OPEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OPY";GRP2="SOP"; LEVELS2="SLF";END;      
  ELSE IF VARNAME="SOP1OPEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OPZ";GRP2="SOP"; LEVELS2="SLF";END;   
  ELSE IF VARNAME="SOP1EREXP" THEN DO; GRP1="EVENT"; LEVELS1="ERT";GRP2="SOP"; LEVELS2="SLF";END;    
  ELSE IF VARNAME="SOP1IPEXP" THEN DO; GRP1="EVENT"; LEVELS1="IPT";GRP2="SOP"; LEVELS2="SLF";END;    
  ELSE IF VARNAME="SOP1HHEXP" THEN DO; GRP1="EVENT"; LEVELS1="HHT";GRP2="SOP"; LEVELS2="SLF";END;   
  ELSE IF VARNAME="SOP1HHEXP_A" THEN DO; GRP1="EVENT"; LEVELS1="HHA";GRP2="SOP"; LEVELS2="SLF";END;   
  ELSE IF VARNAME="SOP1HHEXP_N" THEN DO; GRP1="EVENT"; LEVELS1="HHN";GRP2="SOP"; LEVELS2="SLF";END;   
  ELSE IF VARNAME="SOP1OTEXP" THEN DO; GRP1="EVENT"; LEVELS1="OMA";GRP2="SOP"; LEVELS2="SLF";END;    
  
  ELSE  IF VARNAME="SOP2DVEXP" THEN DO; GRP1="EVENT"; LEVELS1="DVT"; GRP2="SOP"; LEVELS2="PTR";END;
  ELSE IF VARNAME="SOP2RXEXP" THEN DO; GRP1="EVENT"; LEVELS1="RX";GRP2="SOP"; LEVELS2="PTR";END;
  ELSE IF VARNAME="SOP2OBEXP" THEN DO; GRP1="EVENT"; LEVELS1="OBV";GRP2="SOP"; LEVELS2="PTR";END;  
  ELSE IF VARNAME="SOP2OBEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OBD";GRP2="SOP"; LEVELS2="PTR";END;    
  ELSE IF VARNAME="SOP2OBEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OBO";GRP2="SOP"; LEVELS2="PTR";END;    
  ELSE IF VARNAME="SOP2OPEXP" THEN DO; GRP1="EVENT"; LEVELS1="OPT";GRP2="SOP"; LEVELS2="PTR";END;    
  ELSE IF VARNAME="SOP2OPEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OPY";GRP2="SOP"; LEVELS2="PTR";END;      
  ELSE IF VARNAME="SOP2OPEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OPZ";GRP2="SOP"; LEVELS2="PTR";END;   
  ELSE IF VARNAME="SOP2EREXP" THEN DO; GRP1="EVENT"; LEVELS1="ERT";GRP2="SOP"; LEVELS2="PTR";END;    
  ELSE IF VARNAME="SOP2IPEXP" THEN DO; GRP1="EVENT"; LEVELS1="IPT";GRP2="SOP"; LEVELS2="PTR";END;    
  ELSE IF VARNAME="SOP2HHEXP" THEN DO; GRP1="EVENT"; LEVELS1="HHT";GRP2="SOP"; LEVELS2="PTR";END;   
  ELSE IF VARNAME="SOP2HHEXP_A" THEN DO; GRP1="EVENT"; LEVELS1="HHA";GRP2="SOP"; LEVELS2="PTR";END;   
  ELSE IF VARNAME="SOP2HHEXP_N" THEN DO; GRP1="EVENT"; LEVELS1="HHN";GRP2="SOP"; LEVELS2="PTR";END;   
  ELSE IF VARNAME="SOP2OTEXP" THEN DO; GRP1="EVENT"; LEVELS1="OMA";GRP2="SOP"; LEVELS2="PTR";END;  
     
  
  ELSE  IF VARNAME="SOP3DVEXP" THEN DO; GRP1="EVENT"; LEVELS1="DVT"; GRP2="SOP"; LEVELS2="MCR";END;
  ELSE IF VARNAME="SOP3RXEXP" THEN DO; GRP1="EVENT"; LEVELS1="RX";GRP2="SOP"; LEVELS2="MCR";END;
  ELSE IF VARNAME="SOP3OBEXP" THEN DO; GRP1="EVENT"; LEVELS1="OBV";GRP2="SOP"; LEVELS2="MCR";END;  
  ELSE IF VARNAME="SOP3OBEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OBD";GRP2="SOP"; LEVELS2="MCR";END;    
  ELSE IF VARNAME="SOP3OBEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OBO";GRP2="SOP"; LEVELS2="MCR";END;    
  ELSE IF VARNAME="SOP3OPEXP" THEN DO; GRP1="EVENT"; LEVELS1="OPT";GRP2="SOP"; LEVELS2="MCR";END;    
  ELSE IF VARNAME="SOP3OPEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OPY";GRP2="SOP"; LEVELS2="MCR";END;      
  ELSE IF VARNAME="SOP3OPEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OPZ";GRP2="SOP"; LEVELS2="MCR";END;   
  ELSE IF VARNAME="SOP3EREXP" THEN DO; GRP1="EVENT"; LEVELS1="ERT";GRP2="SOP"; LEVELS2="MCR";END;    
  ELSE IF VARNAME="SOP3IPEXP" THEN DO; GRP1="EVENT"; LEVELS1="IPT";GRP2="SOP"; LEVELS2="MCR";END;    
  ELSE IF VARNAME="SOP3HHEXP" THEN DO; GRP1="EVENT"; LEVELS1="HHT";GRP2="SOP"; LEVELS2="MCR";END;   
  ELSE IF VARNAME="SOP3HHEXP_A" THEN DO; GRP1="EVENT"; LEVELS1="HHA";GRP2="SOP"; LEVELS2="MCR";END;   
  ELSE IF VARNAME="SOP3HHEXP_N" THEN DO; GRP1="EVENT"; LEVELS1="HHN";GRP2="SOP"; LEVELS2="MCR";END;   
  ELSE IF VARNAME="SOP3OTEXP" THEN DO; GRP1="EVENT"; LEVELS1="OMA";GRP2="SOP"; LEVELS2="MCR";END;  


  ELSE  IF VARNAME="SOP4DVEXP" THEN DO; GRP1="EVENT"; LEVELS1="DVT"; GRP2="SOP"; LEVELS2="MCD";END;
  ELSE IF VARNAME="SOP4RXEXP" THEN DO; GRP1="EVENT"; LEVELS1="RX";GRP2="SOP"; LEVELS2="MCD";END;
  ELSE IF VARNAME="SOP4OBEXP" THEN DO; GRP1="EVENT"; LEVELS1="OBV";GRP2="SOP"; LEVELS2="MCD";END;  
  ELSE IF VARNAME="SOP4OBEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OBD";GRP2="SOP"; LEVELS2="MCD";END;    
  ELSE IF VARNAME="SOP4OBEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OBO";GRP2="SOP"; LEVELS2="MCD";END;    
  ELSE IF VARNAME="SOP4OPEXP" THEN DO; GRP1="EVENT"; LEVELS1="OPT";GRP2="SOP"; LEVELS2="MCD";END;    
  ELSE IF VARNAME="SOP4OPEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OPY";GRP2="SOP"; LEVELS2="MCD";END;      
  ELSE IF VARNAME="SOP4OPEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OPZ";GRP2="SOP"; LEVELS2="MCD";END;   
  ELSE IF VARNAME="SOP4EREXP" THEN DO; GRP1="EVENT"; LEVELS1="ERT";GRP2="SOP"; LEVELS2="MCD";END;    
  ELSE IF VARNAME="SOP4IPEXP" THEN DO; GRP1="EVENT"; LEVELS1="IPT";GRP2="SOP"; LEVELS2="MCD";END;    
  ELSE IF VARNAME="SOP4HHEXP" THEN DO; GRP1="EVENT"; LEVELS1="HHT";GRP2="SOP"; LEVELS2="MCD";END;   
  ELSE IF VARNAME="SOP4HHEXP_A" THEN DO; GRP1="EVENT"; LEVELS1="HHA";GRP2="SOP"; LEVELS2="MCD";END;   
  ELSE IF VARNAME="SOP4HHEXP_N" THEN DO; GRP1="EVENT"; LEVELS1="HHN";GRP2="SOP"; LEVELS2="MCD";END;   
  ELSE IF VARNAME="SOP4OTEXP" THEN DO; GRP1="EVENT"; LEVELS1="OMA";GRP2="SOP"; LEVELS2="MCD";END;  
  
  ELSE  IF VARNAME="SOP5DVEXP" THEN DO; GRP1="EVENT"; LEVELS1="DVT"; GRP2="SOP"; LEVELS2="OTZ";END;
  ELSE IF VARNAME="SOP5RXEXP" THEN DO; GRP1="EVENT"; LEVELS1="RX";GRP2="SOP"; LEVELS2="OTZ";END;
  ELSE IF VARNAME="SOP5OBEXP" THEN DO; GRP1="EVENT"; LEVELS1="OBV";GRP2="SOP"; LEVELS2="OTZ";END;  
  ELSE IF VARNAME="SOP5OBEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OBD";GRP2="SOP"; LEVELS2="OTZ";END;    
  ELSE IF VARNAME="SOP5OBEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OBO";GRP2="SOP"; LEVELS2="OTZ";END;    
  ELSE IF VARNAME="SOP5OPEXP" THEN DO; GRP1="EVENT"; LEVELS1="OPT";GRP2="SOP"; LEVELS2="OTZ";END;    
  ELSE IF VARNAME="SOP5OPEXP_DR" THEN DO; GRP1="EVENT"; LEVELS1="OPY";GRP2="SOP"; LEVELS2="OTZ";END;      
  ELSE IF VARNAME="SOP5OPEXP_OT" THEN DO; GRP1="EVENT"; LEVELS1="OPZ";GRP2="SOP"; LEVELS2="OTZ";END;   
  ELSE IF VARNAME="SOP5EREXP" THEN DO; GRP1="EVENT"; LEVELS1="ERT";GRP2="SOP"; LEVELS2="OTZ";END;    
  ELSE IF VARNAME="SOP5IPEXP" THEN DO; GRP1="EVENT"; LEVELS1="IPT";GRP2="SOP"; LEVELS2="OTZ";END;    
  ELSE IF VARNAME="SOP5HHEXP" THEN DO; GRP1="EVENT"; LEVELS1="HHT";GRP2="SOP"; LEVELS2="OTZ";END;   
  ELSE IF VARNAME="SOP5HHEXP_A" THEN DO; GRP1="EVENT"; LEVELS1="HHA";GRP2="SOP"; LEVELS2="OTZ";END;   
  ELSE IF VARNAME="SOP5HHEXP_N" THEN DO; GRP1="EVENT"; LEVELS1="HHN";GRP2="SOP"; LEVELS2="OTZ";END;   
  ELSE IF VARNAME="SOP5OTEXP" THEN DO; GRP1="EVENT"; LEVELS1="OMA";GRP2="SOP"; LEVELS2="OTZ";END;  
  

RUN;



PROC SORT DATA=V4R.FYC9614 OUT=REST(KEEP=GRP1 LEVELS1 GRP2 LEVELS2 TOTEXP TOTEXP_SE YEAR);
BY YEAR GRP1 LEVELS1 GRP2 LEVELS2;
RUN;

DATA REST2;
SET REST;
 LENGTH GRP3 GRP4 $15  LEVELS3 LEVELS4 $32;
  GRP3=LOWCASE(COMPRESS(GRP1));
  LEVELS3=LOWCASE(COMPRESS(LEVELS1));
  GRP4=LOWCASE(COMPRESS(GRP2));
  LEVELS4=LOWCASE(COMPRESS(LEVELS2));
RUN;

DATA REST3(DROP=GRP3 GRP4 LEVELS3 LEVELS4);
SET REST2;
  GRP5=GRP3;
  LEVELS5=LEVELS3;
  GRP6=GRP4;
  LEVELS6=LEVELS4;
RUN;


DATA REST4(DROP=GRP5 GRP6 LEVELS5 LEVELS6);
SET REST3;
  GRP4=GRP5;
  LEVELS4=LEVELS5;
  GRP3=GRP6;
  LEVELS3=LEVELS6;
RUN;

DATA REST_ALL;
  SET REST2 REST4;
RUN;

PROC SORT DATA=REST_ALL nodupkey;
  BY YEAR GRP3 LEVELS3 GRP4 LEVELS4;
RUN;


DATA RESULT2;
SET RESULT1;
 LENGTH GRP3 GRP4 $15  LEVELS3 LEVELS4 $32;
  GRP3=LOWCASE(COMPRESS(GRP1));
  LEVELS3=LOWCASE(COMPRESS(LEVELS1));
  GRP4=LOWCASE(COMPRESS(GRP2));
  LEVELS4=LOWCASE(COMPRESS(LEVELS2));
RUN;

PROC SORT DATA=RESULT2 nodupkey;
BY YEAR GRP3 LEVELS3 GRP4 LEVELS4;
RUN;


DATA ALL;
MERGE RESULT2(IN=A KEEP=YEAR GRP3 LEVELS3 GRP4 LEVELS4  SUM STDDEV) REST_ALL(IN=B KEEP=YEAR GRP3 LEVELS3 GRP4 LEVELS4 TOTEXP TOTEXP_SE);
  BY YEAR GRP3 LEVELS3 GRP4 LEVELS4;
  IF A;
  TOTEXPX=TOTEXP/1000000000;
  TOTEXP_SEX=TOTEXP_SE/1000000000;
  SUMX=SUM/1000000000;
  STDDEVX=STDDEV/1000000000;
  DIFF_SUM=abs(round(SUM(TOTEXPX,-SUMX), 0.1));
  DIFF_SE=abs(round(SUM(TOTEXP_SEX, -STDDEVX),0.1));
RUN;


TITLE2 "TOTEXP (in billions) BY CROSS SECTIONAL SOP*EVENT, FOR 1996-2014";
PROC PRINT DATA=ALL(WHERE=(DIFF_SUM NE 0 OR DIFF_SE NE 0)) LABEL;
VAR YEAR GRP3 LEVELS3 GRP4 LEVELS4 TOTEXPx SUMx DIFF_SUM TOTEXP_SEx STDDEVx DIFF_SE;
LABEL TOTEXPx="TOTEXP R"
 SUMx="TOTEXP SAS"
  DIFF_SUM="TOTEXP Diff" 
  TOTEXP_SEx="SE R"
  STDDEVx="SE SAS" 
  DIFF_SE="SE Diff"
  ;
FORMAT TOTEXPx SUMx DIFF_SUM TOTEXP_SEx STDDEVx DIFF_SE COMMA20.1;
RUN;